theme: jekyll-theme-minimal
title: Samuel Swift, Epidemiologist, artist, and friend to the trees

<a href="https://github.com/SamSwift505/samswift505.github.io/raw/main/Crybox_V3.pdf" class="image fit"><img src="images/marr_pic.jpg" alt=""></a>
